### ISSUE TITLE
Add logic to handle Github Action Workflow dependencies on releases

### ISSUE THREAD

**Issue by phenixblue** [tmobile/magtape#23]
**What would you like to be added**:

Add logic to handle Github Action Workflow dependencies on releases

**Why is this needed**:

Currently the release flow executes e2e tests prior to the new container image build because the same flow is used for PR/push to master. Need to make sure image build happens before e2e tests for release prep (push to master). This may require pre-release image builds or refactoring the Github Action workflows overall.

**Comment by Freakin** [comment]
👀

**Comment by phenixblue** [comment]
I think I have a working solution for this. 

- Build images based on current commit (PR or Push to master), but don't push to DockerHub
- Modify version in Makefile to reference new image
- Modify image pull policy in deployment to `ifNotPresent`
- Update single-manifest
- Build KinD cluster
- Load new images directly into kind nodes (`kind load docker-image`)
- Install MagTape
- Run e2e tests
