### ISSUE TITLE
Add Shellcheck CI checks

### ISSUE THREAD

**Issue by phenixblue** [tmobile/magtape#46]
**What would you like to be added**:

Need to add [Shellcheck](https://www.shellcheck.net) CI Checks for all bash scripts in the repo.

**Why is this needed**:

To ensure adherence to a standard for BASH scripts for consistency and best practices. This should help to maintain trusted tooling within the repo.

**Comment by ilrudie** [comment]
I could probably look at this once my existing PR wraps up.

**Comment by phenixblue** [comment]
Thanks @ilrudie , I've assigned this issue to you.

**Comment by ilrudie** [comment]
@phenixblue Got a ci action for shellcheck running in my fork. Shellcheck finds a fair few things to complain about. Should fixing all the bash so shellcheck runs clean be part of this issue?

[example output from my fork](https://github.com/ilrudie/magtape/runs/1247825683?check_suite_focus=true)

**Comment by phenixblue** [comment]
No, I think that should be separate. The Kubernetes project setup a wrapper with an excludes file that lists scripts to skip so as to catch all net new scripts, but not block CI due to existing scripts. I think a similar approach here is good. Then we can to a separate PR per existing script to get stuff fixed over time.

Examples for reference:

- https://github.com/kubernetes/kubernetes/blob/master/hack/verify-shellcheck.sh
- https://github.com/kubernetes/kubernetes/blob/master/hack/.shellcheck_failures

**Comment by ilrudie** [comment]
I can just change how git selection works. Using a file I can add exemptions. This file maybe needs to go in .github/ somewhere.

File example:
```
# Select all .sh files
*.sh

# Exclude the following files under temporary legacy exemption
!hack/build-single-manifest.sh
!hack/patch-ca-bundle.sh
!hack/run-python-tests.sh
!hack/ssl-cert-gen.sh
!testing/export-env.sh
```
