### ISSUE TITLE
Need to update README for Testing

### ISSUE THREAD

**Issue by phenixblue** [tmobile/magtape#56]
**What would you like to be added**:

The testing README located [here](https://github.com/tmobile/magtape/blob/master/testing/README.md) needs to be updated for the most recent changes to the functional testing framework.

Reference #45 for more context

**Why is this needed**:

The existing info is slightly outdated even the changes to `functional-tests.yaml`

**Comment by ilrudie** [comment]
Seems like this should be on me

**Comment by phenixblue** [comment]
Assigned
